# CLONE!!!
# Tutorial
# Message file

0001
...Welcome in the Clone Tutorial...
This level will show you the basis of Clone.
After having read each message, press ~ENTER~ to go
to the next lesson.  To quit the tutorial, press
~ESC~.  If you want to disable auto-pilot mode,
press the ~TAB~ key (Warning: You can only
reactivate auto-pilot by leaving and restarting
the tutorial).

0002
...Crystals and Sockets...
In order to activate some mecanisms, one has to
move Color Crystals over their respective Crystal
Sockets.  Beware not to move Color Crystals
somewhere you won't be able to retrieve them from,
such as too close from a wall or corner.  The Blue
Number indicates how many Crystal Sockets are left
to be triggered.

0003
...One-Ways...
The red One-Ways prevent one from arriving on a
tile from the arrow opposite direction. Though,
you still CAN arrive on the tile from any other
direction and you CAN leave it in whatever
direction you want.

0004
...Trigger Tiles...
The Trigger Tiles also can activate mecanisms.
Just step over them and watch the blue number
decrease of one unit at each time.  Some Trigger
Tiles will remain down, but most of them require
something heavy to be placed over them, such as a
Color Crystal or anything similar.

0005
...Cloning Rune...
The Cloning Rune will duplicate you in two Clones
or more.  Just step over it and meet your little
Clone brother.

0006
...Multiple Trigger Tiles...
When there are many Trigger Tiles to be pressed at
the same time, you can get some help from other
Clones. Try using the obstacles and walls to
offset them till they fit on all Trigger Tiles.

0007
...Uncloning Rune...
The Uncloning Rune will get you back to your
single form.  This is useful when you no longer
need other Clones or are sick of being imitated!

0008
...Objects...
You can pick-up objects by stepping over them.
They will be placed into your inventory on the bar
at the bottom of the screen.  You can use the
selected object with ~SPACEBAR~ or select another
object with ~ALT~.  Here you must place a bomb in
the middle of the rocks in order to blow them
away.  But beware not to stay there!

0009
...Hazards...
Never walk BELOW a Cloud!
Never walk IN FRONT of a Bow!
Never walk ABOVE an Acid Pot!

0010
...Potions and Shields...
Potions and Shields protect against hazards.  But
you must first activate them with ~SPACEBAR~ (then
the tiny potion and shield icons will light-up on
the bar at the bottom of screen).  The yellow
potion is versus lightnings, green versus acid,
red versus fire, blue versus ice and the shield
protects against arrows.

0011
...Spikes...
Spikes are dangerous hazards!  Never arrive on
them from the opposite direction!  But you can
arrive from any other direction and leave in
whatever direction you want, just like red
One-Ways!

0012
...Buttons & Levers...
One other way to activate mecanisms is yet to use
push buttons and levers.  Push buttons can be used
only once, while levers can be triggered
indefinitely to do or undo the actions it has been
assigned to.

0013
...The Big Blue Jewel...
The Big Blue Jewel is the ultimate goal of each
level, because it will transport you to the next
level.  Note that you have to bring all Clones
that are still alive to the jewel in order to
complete a level.

0014
...End of Tutorial...
Here comes the end of the Clone lessons!  You
might want to try this Tutorial without auto-pilot
(press ~TAB~ the next time you start the Tutorial)
or read the on-line help screen (press ~F1~ while
playing a level) and bundled ~CLONE.TXT~ file.
Now, enjoy the Clone adventure!!!

9000
!!! HELP !!!
  ~SPACE~ = Use Object       ~P~ = Pause
    ~ALT~ = Cycle Inventory  ~M~ = Toggle Music
   ~CTRL~ = Stop or Turn     ~F~ = Toggle FX
      ~A~ = Abort & retry    ~S~ = Toggle Sound
ÿ
  ~ENTER~ = Toggle Menu      ~F1~ = Help!!!
    ~ESC~ = Main Menu        ~F2~ = Joystick Help!!!
ÿ
  ~PgUp~/~PgDn~ = Scroll Screen Up or Down
~Scroll Lock~ = Lock/Unlock Auto-Scrolling

9001
!!! Joystick HELP !!!
~Joystick A~
    Button ~#1~ = Use Object
    Button ~#2~ = Cycle Inventory
   (Button ~#3~ = Stop or Turn)
   (Button ~#4~ = Toggle Menu)
ÿ
~Joystick B~
    ~Up~ Or ~Down~ = Scroll Screen

