# CLONE!!!
# World 00 : Mornack's Castles
# Message file

0001
...Welcome...
Welcome in my world of castles, little blue being!
Hope you enjoy my puzzles! AhAhah...
ÿ
                                          Mornack.
ÿ
NB: If you're stuck, press ~A~ to abort and retry
the puzzle.  To access a quick keyboard reference,
press ~F1~ for HELP!!!

0002
...Protections...
May these enchanted items help you go through this
puzzle...  Don't forget to activate them BEFORE
facing the hazards!
ÿ
Press ~ALT~ to cycle through your inventory
Press ~SPACE~ to use the currently selected item
ÿ
                                The Lonely Spirit.

0003
...Floating Guardians...
Never dare look toward them : Their glare is of
fire.  Just look in the opposite direction and
they won't stare at you.
ÿ
                         The Voice In The Ceiling.

0004
...Frantic Arachnids...
Frantic Arachnids have nine eyes!  Never stay in
their sight!  If one happens to see you, you'd
better quickly hide behind a wall or you're as
good as dead!
ÿ
                                       The Entity.

0005
...Bombs...
Warning: Explosions cover a 3 by 3 tiles square
area, so you'd better avoid standing near!
ÿ
                           The FiReWoRkS mAgIcIaN.

9000
!!! HELP !!!
  ~SPACE~ = Use Object       ~P~ = Pause
    ~ALT~ = Cycle Inventory  ~M~ = Toggle Music
   ~CTRL~ = Stop or Turn     ~F~ = Toggle FX
      ~A~ = Abort & retry    ~S~ = Toggle Sound
ÿ
  ~ENTER~ = Toggle Menu      ~F1~ = Help!!!
    ~ESC~ = Main Menu        ~F2~ = Joystick Help!!!
ÿ
  ~PgUp~/~PgDn~ = Scroll Screen Up or Down
~Scroll Lock~ = Lock/Unlock Auto-Scrolling

9001
!!! Joystick HELP !!!
~Joystick A~
    Button ~#1~ = Use Object
    Button ~#2~ = Cycle Inventory
   (Button ~#3~ = Stop or Turn)
   (Button ~#4~ = Toggle Menu)
ÿ
~Joystick B~
    ~Up~ Or ~Down~ = Scroll Screen

