# CLONE!!!
# World 02 : Ground Bowels
# Message file

0001
...Bombs...
Warning: Explosions cover a 3 by 3 tiles square
area, so you'd better avoid standing near!
ÿ
                           The FiReWoRkS mAgIcIaN.

0002
...Sarcasm Devils...
Don't become one of theirs!!!  They are spreading
like a plague!!!  Avoid them and never try to
defeat them...
ÿ
                                The Hidden Priest.

0003
...Fire Gargoyles...
Never let them touch you, but you may try to touch
them.  If you approach them in their back, they
won't see you...  Beware, they are vicious
creatures with strange powers...
ÿ
                               The Talking Statue.

0004
...The Moment...
No need to run...
      Just do things...
            At the right moment...
ÿ
                      The Lunatic Sat on the Moon.

0005
...Pessimistic...
This is a particular puzzle that can quickly
become unsolvable at the first wrong move.
If you're stuck, don't persist in keeping
going : You'd better retry it from start.
ÿ
                          The Pessimistic Thought.

0006
...Humanoid Shape...
Stone is my skin, lava is my blood,
Walk on my eyes, rip my nose quite odd...
Travel through my body, reach my feet
And then your goal you will surely meet...

0007
...Fire Ballistics Note...
Casting a fire ball at a distant target
produces a wide explosion, while shooting
it at a close target causes only a small
burst...

9000
!!! HELP !!!
  ~SPACE~ = Use Object       ~P~ = Pause
    ~ALT~ = Cycle Inventory  ~M~ = Toggle Music
   ~CTRL~ = Stop or Turn     ~F~ = Toggle FX
      ~A~ = Abort & retry    ~S~ = Toggle Sound
ÿ
  ~ENTER~ = Toggle Menu      ~F1~ = Help!!!
    ~ESC~ = Main Menu        ~F2~ = Joystick Help!!!
ÿ
  ~PgUp~/~PgDn~ = Scroll Screen Up or Down
~Scroll Lock~ = Lock/Unlock Auto-Scrolling

9001
!!! Joystick HELP !!!
~Joystick A~
    Button ~#1~ = Use Object
    Button ~#2~ = Cycle Inventory
   (Button ~#3~ = Stop or Turn)
   (Button ~#4~ = Toggle Menu)
ÿ
~Joystick B~
    ~Up~ Or ~Down~ = Scroll Screen

