# CLONE!!!
# World 01 : Frozen Mountains
# Message file

0001
...Dragons of Confusion...
Dragons of Confusion are misleading!
ÿ
                            The Dragon Egg Hunter.

0002
...Ice Scroll...
Press SPACEBAR while the Ice Cube is selected in
your inventory to cast the Spell of Absolute Zero
in the direction you're heading.
ÿ
                                 The Chilly Thing.

9000
!!! HELP !!!
  ~SPACE~ = Use Object       ~P~ = Pause
    ~ALT~ = Cycle Inventory  ~M~ = Toggle Music
   ~CTRL~ = Stop or Turn     ~F~ = Toggle FX
      ~A~ = Abort & retry    ~S~ = Toggle Sound
ÿ
  ~ENTER~ = Toggle Menu      ~F1~ = Help!!!
    ~ESC~ = Main Menu        ~F2~ = Joystick Help!!!
ÿ
  ~PgUp~/~PgDn~ = Scroll Screen Up or Down
~Scroll Lock~ = Lock/Unlock Auto-Scrolling

9001
!!! Joystick HELP !!!
~Joystick A~
    Button ~#1~ = Use Object
    Button ~#2~ = Cycle Inventory
   (Button ~#3~ = Stop or Turn)
   (Button ~#4~ = Toggle Menu)
ÿ
~Joystick B~
    ~Up~ Or ~Down~ = Scroll Screen

