# CLONE!!!
# World 04 : Future Destiny
# Message file

9000
!!! HELP !!!
  ~SPACE~ = Use Object       ~P~ = Pause
    ~ALT~ = Cycle Inventory  ~M~ = Toggle Music
   ~CTRL~ = Stop or Turn     ~F~ = Toggle FX
      ~A~ = Abort & retry    ~S~ = Toggle Sound
ÿ
  ~ENTER~ = Toggle Menu      ~F1~ = Help!!!
    ~ESC~ = Main Menu        ~F2~ = Joystick Help!!!
ÿ
  ~PgUp~/~PgDn~ = Scroll Screen Up or Down
~Scroll Lock~ = Lock/Unlock Auto-Scrolling

9001
!!! Joystick HELP !!!
~Joystick A~
    Button ~#1~ = Use Object
    Button ~#2~ = Cycle Inventory
   (Button ~#3~ = Stop or Turn)
   (Button ~#4~ = Toggle Menu)
ÿ
~Joystick B~
    ~Up~ Or ~Down~ = Scroll Screen

